name: Build Example

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.6'
      - name: Update submodules
        run: git submodule update --init
      - name: Build Example
        run: cd example && make
      - name: Run Tests
        run: go test -v ./...
